---
title: "LIS 4370 Module 12"
output: html_document
---

## Create readCensus()

Create the readCensus() function. It should be able to clean out NA data, excess rows & columns, and unecessary punctuation including commas and periods in the data. After cleaning, the data should be fully prepared for analysis.


```{r}
readCensus <- function(csv) 
{ 
  data <- read.csv(url(csv)) 
  
  data <- data[-66:-60,] 
  data <- data[-8:-1,] 
  data <- data[,-10:-6] 
  cnames <- c("stateName","april10census","april10base","july10pop","july11pop") 
  colnames(data) <- cnames 
  
  data$april10census <- gsub(",", "", data$april10census) 
  data$april10base <- gsub(",", "", data$april10base) 
  data$july10pop <- gsub(",", "", data$july10pop) 
  data$july11pop <- gsub(",", "", data$july11pop) 
  
  data$april10census <- as.numeric(data$april10census) 
  data$april10base <- as.numeric(data$april10base) 
  data$july10pop <- as.numeric(data$july10pop) 
  data$july11pop <- as.numeric(data$july11pop) 
  
  data$stateName <- gsub("\\.", "", data$stateName)
  
  return(data) 
}


```

## Run Function

Run the function on the following csv file:
http://www2.census.gov/programs-surveys/popest/tables/2010-2011/state/totals/nst-est2011-01.csv

```{r}
dfStates <- readCensus("http://www2.census.gov/programs-surveys/popest/tables/2010-2011/state/totals/nst-est2011-01.csv")

```
